// Dati dei 6 trattamenti: una pagina ciascuno (slug.html) + card in home e in trattamenti.html.
// Fonti dei fatti "Da sapere" (verificate il 2026-10-02):
// - amalgama: Regolamento (UE) 2024/1849, in vigore dal 1° gennaio 2025 (ANDI)
// - sbiancamento: Direttiva 2011/84/UE (perossido di idrogeno 0,1–6% solo tramite dentista, vietato ai minori di 18 anni)
// - sigillature: Linee guida nazionali del Ministero della Salute (età evolutiva, 2013), primi molari a 6–7 anni
// - allineatori: circa 22 ore al giorno, contenzione a fine trattamento
// - sedazione cosciente con protossido d'azoto: eseguibile dall'odontoiatra, nei bambini collaboranti dai 4 anni circa
// - gengive: gengive sane non sanguinano; controllo se il sanguinamento non migliora in 10–14 giorni
module.exports = [
  {
    slug: 'igiene-dentale', id: 'igiene', icon: 'igiene', menu: 'Igiene e prevenzione', title: 'Igiene e prevenzione',
    short: 'Pulizia professionale, controllo delle gengive e consigli pratici per la cura quotidiana a casa.',
    home: ['cura-a-casa.webp', 'Spazzolino in bambù, scovolini e filo interdentale su un telo di lino'],
    img: 'vassoio-profilassi.webp', alt: 'Il vassoio preparato per una seduta di igiene, con pasta per la pulizia e coppette lucidanti',
    seo: 'Igiene dentale professionale a Milano',
    desc: 'Pulizia dei denti professionale a Milano, zona Wagner: cosa include la seduta di igiene, ogni quanto farla, se fa male e cosa usare a casa.',
    lead: 'Una seduta di igiene ogni sei mesi è il modo più semplice per prevenire carie e malattie delle gengive. È anche il momento in cui impari cosa usare a casa.',
    cos: 'La seduta di igiene professionale rimuove placca e tartaro dove lo spazzolino non arriva. Include il controllo delle gengive e indicazioni sugli strumenti da usare a casa.',
    chi: 'Per tutti, adulti e bambini. È particolarmente indicata a chi ha gengive che sanguinano, porta apparecchi o impianti, è in gravidanza o fuma.',
    come: 'L\'igienista usa ultrasuoni e strumenti manuali, poi lucida le superfici dei denti. Se c\'è sensibilità, si può applicare un anestetico locale in gel o si procede per zone.',
    dura: 'Circa 45–60 minuti. Di solito si ripete ogni 6 mesi; l\'intervallo può essere diverso in base alla situazione delle gengive.',
    sapere: [
      'Le gengive sane non sanguinano. Se sanguinano spesso quando ti lavi i denti, è il primo segnale di un\'infiammazione da far controllare.',
      'Il tartaro non si toglie con lo spazzolino: si forma dalla placca che resta sui denti e si rimuove solo con strumenti professionali.',
      'Con impianti, apparecchi o una storia di problemi alle gengive, l\'igienista può consigliare richiami più frequenti, anche ogni 3–4 mesi.',
      'In gravidanza la seduta di igiene si può fare ed è utile: i cambiamenti ormonali rendono le gengive più sensibili all\'infiammazione.',
    ],
    faq: [
      ['La pulizia dei denti fa male?', 'Di solito no: si sente una vibrazione e un po\' di sensibilità dove il tartaro è sotto la gengiva. Se sei sensibile dillo all\'igienista: si può usare un anestetico in gel o procedere per zone.'],
      ['Rovina lo smalto?', 'No. Gli strumenti agiscono su placca e tartaro, non sullo smalto. Nei giorni successivi i denti possono essere un po\' più sensibili al freddo: è normale e passa da sé.'],
      ['Cosa devo usare a casa oltre allo spazzolino?', 'Dipende dagli spazi tra i denti: filo interdentale dove sono stretti, scovolini dove sono più ampi. Durante la seduta l\'igienista ti indica la misura giusta e come usarli.'],
    ],
    team: ['Dott.ssa Giulia Sorelli', 'Igienista dentale'],
  },
  {
    slug: 'conservativa', id: 'conservativa', icon: 'conservativa', menu: 'Conservativa', title: 'Conservativa',
    short: 'Cura della carie e ricostruzione dei denti danneggiati, cercando di conservare quanto più dente naturale possibile.',
    home: ['conservativa-strumenti.webp', 'Strumenti per la conservativa su un vassoio, con un modello di arcate sullo sfondo'],
    img: 'tr-conservativa.webp', alt: 'Il dentista parla con una paziente seduta, entrambi sorridenti',
    seo: 'Cura della carie e otturazioni a Milano',
    desc: 'Cura della carie e otturazioni in composito a Milano, zona Wagner: come si svolge, quanto dura, se serve l\'anestesia e cosa cambia dopo lo stop all\'amalgama.',
    lead: 'Curare una carie quando è piccola richiede una seduta breve e quasi sempre senza dolore. Aspettare rende la cura più lunga e più impegnativa.',
    cos: 'È la cura dei denti colpiti da carie o scheggiati. Si rimuove la parte danneggiata e si ricostruisce il dente con materiali compositi del colore del dente.',
    chi: 'Per chi ha una carie individuata durante un controllo, un\'otturazione vecchia da sostituire, sensibilità al freddo o un dente rotto.',
    come: 'Dopo l\'anestesia locale si isola il dente, si pulisce la cavità e si applica il materiale a strati. Alla fine si controlla che il morso sia corretto.',
    dura: 'Da 30 a 60 minuti per dente, in una sola seduta. Nelle ricostruzioni più ampie può servire un secondo appuntamento.',
    sapere: [
      'Dal 1° gennaio 2025, per un regolamento europeo, l\'amalgama (le vecchie otturazioni grigie che contengono mercurio) non si usa più, salvo esigenze mediche specifiche. Si usano materiali compositi del colore del dente.',
      'Le vecchie otturazioni in amalgama integre non vanno per forza sostituite: le controlliamo a ogni visita e le cambiamo solo se sono rovinate o se c\'è una carie sotto.',
      'Una carie trascurata può arrivare alla polpa, il cosiddetto nervo: a quel punto serve una devitalizzazione, una cura più lunga.',
      'Una sensibilità al freddo o al dolce che dura nel tempo è un buon motivo per prenotare un controllo.',
    ],
    faq: [
      ['Serve sempre l\'anestesia?', 'Quasi sempre, ma non sempre: per carie molto superficiali a volte non serve. Prima dell\'iniezione applichiamo un gel anestetico sulla gengiva, così la puntura si sente appena.'],
      ['Quanto dura un\'otturazione in composito?', 'Molti anni, se curata con igiene e controlli regolari. La durata dipende da dimensione e posizione dell\'otturazione e da abitudini come il digrignare i denti di notte.'],
      ['Dopo posso mangiare subito?', 'Il composito indurisce subito con una luce apposita, quindi sì. Aspetta però che finisca l\'effetto dell\'anestesia, per non morderti guance o labbra senza accorgertene.'],
    ],
    team: ['Dott. Lorenzo Valdieri', 'Odontoiatra'],
  },
  {
    slug: 'ortodonzia', id: 'ortodonzia', icon: 'ortodonzia', menu: 'Ortodonzia', title: 'Ortodonzia, anche invisibile',
    short: 'Apparecchi fissi e allineatori trasparenti per bambini, ragazzi e adulti.',
    home: ['allineatori.webp', 'Allineatori trasparenti appoggiati su una pietra chiara'],
    img: 'arcate.webp', alt: 'Modello di arcate dentali visto da vicino, con i denti superiori e inferiori a contatto',
    seo: 'Ortodonzia e allineatori trasparenti a Milano',
    desc: 'Ortodonzia a Milano, zona Wagner: apparecchi fissi e allineatori trasparenti per bambini, ragazzi e adulti. Quando iniziare, quanto dura, cosa aspettarsi.',
    lead: 'Denti più allineati si puliscono meglio e masticano meglio. Si può correggere la loro posizione a ogni età, con apparecchi fissi o allineatori trasparenti.',
    cos: 'Corregge la posizione dei denti e il rapporto tra le arcate. Si usano apparecchi fissi, mobili oppure allineatori trasparenti rimovibili, a seconda del caso.',
    chi: 'Per bambini dai 6–7 anni, per una prima valutazione della crescita, e per ragazzi e adulti con denti affollati, distanziati o un morso non corretto.',
    come: 'Si parte da visita, radiografie e scansione digitale delle arcate. L\'ortodontista propone il tipo di apparecchio e segue il trattamento con controlli periodici.',
    dura: 'In genere da 12 a 24 mesi, con controlli ogni 6–8 settimane. Segue una fase di mantenimento con un contenitore.',
    sapere: [
      'La prima visita ortodontica è consigliata verso i 6–7 anni: alcuni problemi di crescita delle ossa si correggono più facilmente mentre il bambino si sviluppa.',
      'Gli allineatori trasparenti funzionano se si portano circa 22 ore al giorno: si tolgono solo per mangiare e per lavare i denti.',
      'Non c\'è un\'età limite: anche da adulti si può correggere la posizione dei denti, se denti e gengive sono in salute.',
      'Finito il trattamento serve una contenzione, un filo sottile incollato dietro i denti o una mascherina, per mantenere il risultato nel tempo.',
    ],
    faq: [
      ['Meglio l\'apparecchio fisso o gli allineatori?', 'Dipende dal caso. Gli allineatori sono comodi e quasi invisibili ma richiedono costanza; il fisso lavora sempre ed è indicato per alcuni movimenti più complessi. Lo decide l\'ortodontista dopo la visita.'],
      ['L\'apparecchio fa male?', 'Nei primi giorni e dopo ogni regolazione o cambio di mascherina i denti possono essere indolenziti per 2–3 giorni. È normale e passa da sé.'],
      ['Posso fare sport o suonare uno strumento?', 'Sì. Per gli sport di contatto consigliamo un paradenti; con gli strumenti a fiato serve qualche giorno per abituarsi.'],
    ],
    team: ['Dott.ssa Camilla Ardenghi', 'Ortodontista'],
  },
  {
    slug: 'implantologia', id: 'implantologia', icon: 'implantologia', menu: 'Implantologia', title: 'Implantologia',
    short: 'Sostituzione di uno o più denti mancanti con impianti in titanio e corone fisse.',
    home: ['radiografie-impianto.webp', 'Radiografie e ricostruzioni 3D delle arcate preparate per pianificare un impianto'],
    img: 'tr-implantologia.webp', alt: 'Il dentista spiega una radiografia sullo schermo a una paziente',
    seo: 'Impianti dentali a Milano',
    desc: 'Impianti dentali a Milano, zona Wagner: come si svolge l\'intervento, i tempi di guarigione, se fa male, quanto dura un impianto e come curarlo.',
    lead: 'Un impianto sostituisce la radice di un dente mancante e sostiene una corona fissa. Prima di proporlo verifichiamo con gli esami che ci siano le condizioni giuste.',
    cos: 'Un impianto è una piccola vite in titanio inserita nell\'osso al posto della radice di un dente mancante. Sopra si fissa una corona, un ponte o una protesi.',
    chi: 'Per adulti che hanno perso uno o più denti. L\'indicazione dipende dalla quantità di osso e dallo stato di salute generale, valutati in visita.',
    come: 'Dopo gli esami radiografici, l\'impianto si inserisce in anestesia locale. Si attende l\'integrazione con l\'osso, poi si realizza e si fissa la corona definitiva.',
    dura: 'L\'intervento richiede circa un\'ora per impianto. L\'integrazione con l\'osso richiede di norma da 3 a 6 mesi; il percorso si allunga se prima serve rigenerare l\'osso.',
    sapere: [
      'Prima dell\'intervento servono esami radiografici, spesso una TAC a basso dosaggio (cone beam), per misurare l\'osso disponibile e pianificare la posizione dell\'impianto.',
      'Il fumo e il diabete non controllato aumentano il rischio che l\'impianto non si integri: ne parliamo apertamente durante la visita.',
      'In alcuni casi si può applicare un dente provvisorio fisso già nei giorni dell\'intervento (carico immediato). Non è adatto a tutti: dipende dall\'osso e dal tipo di intervento.',
      'Un impianto va pulito come un dente naturale, a casa e con i richiami di igiene: senza, i tessuti intorno possono infiammarsi (perimplantite).',
    ],
    faq: [
      ['L\'intervento fa male?', 'Si esegue in anestesia locale, come un\'otturazione, quindi durante l\'intervento non si sente dolore. Nei giorni seguenti possono esserci gonfiore e fastidio, gestibili con i farmaci che ti indichiamo.'],
      ['Quanto dura un impianto?', 'Se l\'osso guarisce bene e l\'igiene è curata, un impianto può durare moltissimi anni. Non è garantito a vita: contano i controlli, la pulizia e abitudini come il fumo.'],
      ['Resto senza denti durante la guarigione?', 'No. Di norma si applica un provvisorio, fisso o rimovibile, così puoi parlare e sorridere normalmente mentre l\'impianto si integra con l\'osso.'],
    ],
    team: ['Dott. Lorenzo Valdieri', 'Odontoiatra · Master in Implantologia'],
  },
  {
    slug: 'pedodonzia', id: 'pedodonzia', icon: 'pedodonzia', menu: 'Dentista per bambini', title: 'Pedodonzia: il dentista dei bambini',
    short: 'Le prime visite dei bambini, la prevenzione della carie e la cura dei denti da latte.',
    home: ['prevenzione-bimbi.webp', 'Spazzolino, dentifricio per bambini, adesivi e clessidra su un vassoio di legno'],
    img: 'lumea-kids.webp', alt: 'La sala dedicata ai bambini, con una poltrona colorata, libri e giochi',
    seo: 'Dentista per bambini a Milano',
    desc: 'Dentista per bambini a Milano, zona Wagner: quando fare la prima visita, sigillature, cura dei denti da latte e come preparare il bambino.',
    lead: 'Una prima visita serena rende più facili tutte le successive. Andiamo con i tempi del bambino, e il genitore resta sempre con lui.',
    cos: 'È l\'odontoiatria dedicata ai bambini: controlli, prevenzione della carie, sigillature dei solchi e cura dei denti da latte e dei primi permanenti.',
    chi: 'Per bambini a partire dai 2 anni circa, come consigliano le raccomandazioni del Ministero della Salute. La prima visita è utile anche senza problemi evidenti, per abituare il bambino all\'ambiente.',
    come: 'Il genitore resta nella stanza. Mostriamo al bambino gli strumenti prima di usarli e procediamo con i suoi tempi; se serve, si divide il lavoro in più appuntamenti brevi.',
    dura: 'Un controllo richiede circa 30 minuti. Consigliamo una visita ogni 6 mesi.',
    sapere: [
      'Le linee guida del Ministero della Salute raccomandano la sigillatura dei solchi dei primi molari permanenti verso i 6–7 anni: protegge le superfici dove la carie compare più spesso.',
      'Anche i denti da latte vanno curati: servono per masticare e parlare bene e tengono il posto ai denti definitivi.',
      'Finché il bambino non è autonomo, un adulto lo aiuta a lavarsi i denti. La quantità di dentifricio al fluoro cambia con l\'età: te la indichiamo in visita.',
      'Per i bambini molto ansiosi, dai 4 anni circa, in alcuni casi si può valutare la sedazione cosciente con protossido d\'azoto: il bambino resta sveglio e tranquillo.',
    ],
    faq: [
      ['Come preparo mio figlio alla prima visita?', 'Parlane in modo semplice e positivo, senza usare il dentista come minaccia e senza promettere che "non farà niente". Spesso la prima volta si guardano e si contano i denti, e basta.'],
      ['Posso restare con lui durante la visita?', 'Sì, sempre. Per i più piccoli è la cosa più rassicurante, e ci aiuta a capire come sta.'],
      ['E se il bambino non collabora?', 'Ci fermiamo e riproviamo un\'altra volta, con appuntamenti brevi. Forzare una visita rende più difficili tutte le successive.'],
    ],
    team: ['Dott.ssa Camilla Ardenghi e Dott.ssa Giulia Sorelli', 'Ortodontista e igienista'],
  },
  {
    slug: 'estetica-dentale', id: 'estetica', icon: 'estetica', menu: 'Estetica dentale', title: 'Estetica dentale',
    short: 'Sbiancamento professionale e faccette, valutati dopo una visita e solo se indicati.',
    home: ['conservativa-estetica.webp', 'Modello di arcata dentale su un vassoio di legno'],
    img: 'tr-estetica.webp', alt: 'Una ragazza sorride guardandosi allo specchio',
    seo: 'Sbiancamento e faccette a Milano',
    desc: 'Sbiancamento dentale professionale e faccette a Milano, zona Wagner: come funzionano, per chi sono indicati, cosa prevede la normativa europea.',
    lead: 'Sbiancamento e faccette si valutano solo su denti e gengive in salute. Ti diciamo con onestà cosa si può ottenere, e cosa no.',
    cos: 'Comprende lo sbiancamento professionale e le faccette, sottili lamine in ceramica o composito applicate sulla superficie visibile dei denti.',
    chi: 'Per adulti con denti e gengive in salute che desiderano modificare colore o forma dei denti. Non è indicata in presenza di carie o infiammazioni non curate.',
    come: 'Dopo una seduta di igiene, lo sbiancamento si esegue in studio o a domicilio con mascherine personalizzate. Le faccette richiedono una scansione e un periodo di prova.',
    dura: 'Lo sbiancamento in studio richiede una seduta di circa 60–90 minuti; a domicilio 2–3 settimane. Per le faccette servono in genere 3 appuntamenti in un mese.',
    sapere: [
      'Per una direttiva europea, i prodotti sbiancanti con perossido di idrogeno oltre lo 0,1% (fino al 6%) si possono usare solo tramite il dentista, dopo una visita e un primo trattamento in studio.',
      'Lo sbiancamento non si esegue sui minori di 18 anni.',
      'Lo sbiancamento non cambia il colore di otturazioni, corone o faccette già presenti: se ci sono, ne teniamo conto nel piano.',
      'Dopo lo sbiancamento è normale una sensibilità temporanea al freddo, che si riduce nel giro di pochi giorni.',
    ],
    faq: [
      ['Quanto dura il risultato dello sbiancamento?', 'Varia da persona a persona: caffè, tè, vino rosso e fumo lo riducono nel tempo. Si può mantenere con brevi richiami a domicilio indicati dal dentista.'],
      ['Le faccette rovinano i denti?', 'A volte per applicarle si leviga un sottile strato di smalto, altre volte quasi nulla: dipende dal caso. Te lo spieghiamo prima, così decidi sapendo cosa comporta.'],
      ['Posso usare i kit sbiancanti in vendita?', 'Quelli in libera vendita contengono al massimo lo 0,1% di perossido di idrogeno, con un effetto limitato. Prodotti più forti comprati online fuori dai canali previsti possono irritare gengive e denti.'],
    ],
    team: ['Dott. Lorenzo Valdieri', 'Odontoiatra'],
  },
];
